@apiURL = http://localhost:5000/api

### Реєстрація
POST {{apiURL}}/auth/register
Content-Type: application/json

{
    "name": "Test User",
    "email": "donthavenikname@gmail.com",
    "password": "Nik_0402",
    "role": "customer"
}

### Вхід
POST {{apiURL}}/auth/login
Content-Type: application/json

{
    "email": "kitnikita06@gmail.com",
    "password": "Nik_0404"
}

### Надсилання токена для зміни пароля
POST {{apiURL}}/auth/password-reset
Content-Type: application/json

{
    "email": "kitnikita06@gmail.com"
}

### Зміна пароля
POST {{apiURL}}/auth/password-change/82cd8dc87216b47103e6450cd980cb80905343cb8ecabe13937e89d8743a6bc6

Content-Type: application/json

{
    "password": "Nik_0402"
}

### Видалення користувача
DELETE {{apiURL}}/user/